/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsNovoRouteImport } from './routes/tickets.novo'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as SatisfacaoTokenRouteImport } from './routes/satisfacao.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksAutoCloseTicketsRouteImport } from './routes/api/public/hooks/auto-close-tickets'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNovoRoute = TicketsNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const SatisfacaoTokenRoute = SatisfacaoTokenRouteImport.update({
  id: '/satisfacao/$token',
  path: '/satisfacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoCloseTicketsRoute =
  ApiPublicHooksAutoCloseTicketsRouteImport.update({
    id: '/api/public/hooks/auto-close-tickets',
    path: '/api/public/hooks/auto-close-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/login'
    | '/tickets'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-close-tickets'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/login'
    | '/tickets'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-close-tickets'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/login'
    | '/tickets'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-close-tickets'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  LoginRoute: typeof LoginRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SatisfacaoTokenRoute: typeof SatisfacaoTokenRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAutoCloseTicketsRoute: typeof ApiPublicHooksAutoCloseTicketsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/novo': {
      id: '/tickets/novo'
      path: '/novo'
      fullPath: '/tickets/novo'
      preLoaderRoute: typeof TicketsNovoRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/satisfacao/$token': {
      id: '/satisfacao/$token'
      path: '/satisfacao/$token'
      fullPath: '/satisfacao/$token'
      preLoaderRoute: typeof SatisfacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-close-tickets': {
      id: '/api/public/hooks/auto-close-tickets'
      path: '/api/public/hooks/auto-close-tickets'
      fullPath: '/api/public/hooks/auto-close-tickets'
      preLoaderRoute: typeof ApiPublicHooksAutoCloseTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsNovoRoute: typeof TicketsNovoRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
  TicketsNovoRoute: TicketsNovoRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  LoginRoute: LoginRoute,
  TicketsRoute: TicketsRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SatisfacaoTokenRoute: SatisfacaoTokenRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAutoCloseTicketsRoute: ApiPublicHooksAutoCloseTicketsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
