/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrabalhosRouteImport } from './routes/trabalhos'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as PreventivaRouteImport } from './routes/preventiva'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreventivaIndexRouteImport } from './routes/preventiva.index'
import { Route as TrabalhosIdRouteImport } from './routes/trabalhos_.$id'
import { Route as TicketsNovoRouteImport } from './routes/tickets.novo'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as SatisfacaoTokenRouteImport } from './routes/satisfacao.$token'
import { Route as PreventivaAgendamentosRouteImport } from './routes/preventiva_.agendamentos'
import { Route as PreventivaTemplatesRouteImport } from './routes/preventiva.templates'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminFaturacaoRouteImport } from './routes/admin.faturacao'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as PreventivaTemplatesIdRouteImport } from './routes/preventiva_.templates.$id'
import { Route as PreventivaRelatorioIdRouteImport } from './routes/preventiva_.relatorio.$id'
import { Route as PreventivaExecucaoIdRouteImport } from './routes/preventiva_.execucao.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicSatisfacaoTokenRouteImport } from './routes/api/public/satisfacao.$token'
import { Route as ApiPublicHooksAutoCloseTicketsRouteImport } from './routes/api/public/hooks/auto-close-tickets'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosRoute = TrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaRoute = PreventivaRouteImport.update({
  id: '/preventiva',
  path: '/preventiva',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaIndexRoute = PreventivaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreventivaRoute,
} as any)
const TrabalhosIdRoute = TrabalhosIdRouteImport.update({
  id: '/trabalhos_/$id',
  path: '/trabalhos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNovoRoute = TicketsNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const SatisfacaoTokenRoute = SatisfacaoTokenRouteImport.update({
  id: '/satisfacao/$token',
  path: '/satisfacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaAgendamentosRoute = PreventivaAgendamentosRouteImport.update({
  id: '/preventiva_/agendamentos',
  path: '/preventiva/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaTemplatesRoute = PreventivaTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PreventivaRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaturacaoRoute = AdminFaturacaoRouteImport.update({
  id: '/admin/faturacao',
  path: '/admin/faturacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaTemplatesIdRoute = PreventivaTemplatesIdRouteImport.update({
  id: '/preventiva_/templates/$id',
  path: '/preventiva/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaRelatorioIdRoute = PreventivaRelatorioIdRouteImport.update({
  id: '/preventiva_/relatorio/$id',
  path: '/preventiva/relatorio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivaExecucaoIdRoute = PreventivaExecucaoIdRouteImport.update({
  id: '/preventiva_/execucao/$id',
  path: '/preventiva/execucao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSatisfacaoTokenRoute =
  ApiPublicSatisfacaoTokenRouteImport.update({
    id: '/api/public/satisfacao/$token',
    path: '/api/public/satisfacao/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCloseTicketsRoute =
  ApiPublicHooksAutoCloseTicketsRouteImport.update({
    id: '/api/public/hooks/auto-close-tickets',
    path: '/api/public/hooks/auto-close-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/preventiva': typeof PreventivaRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/trabalhos': typeof TrabalhosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/preventiva/templates': typeof PreventivaTemplatesRoute
  '/preventiva/agendamentos': typeof PreventivaAgendamentosRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/trabalhos/$id': typeof TrabalhosIdRoute
  '/preventiva/': typeof PreventivaIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/preventiva/execucao/$id': typeof PreventivaExecucaoIdRoute
  '/preventiva/relatorio/$id': typeof PreventivaRelatorioIdRoute
  '/preventiva/templates/$id': typeof PreventivaTemplatesIdRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/satisfacao/$token': typeof ApiPublicSatisfacaoTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trabalhos': typeof TrabalhosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/preventiva/templates': typeof PreventivaTemplatesRoute
  '/preventiva/agendamentos': typeof PreventivaAgendamentosRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/trabalhos/$id': typeof TrabalhosIdRoute
  '/preventiva': typeof PreventivaIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/preventiva/execucao/$id': typeof PreventivaExecucaoIdRoute
  '/preventiva/relatorio/$id': typeof PreventivaRelatorioIdRoute
  '/preventiva/templates/$id': typeof PreventivaTemplatesIdRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/satisfacao/$token': typeof ApiPublicSatisfacaoTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/login': typeof LoginRoute
  '/preventiva': typeof PreventivaRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/trabalhos': typeof TrabalhosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/faturacao': typeof AdminFaturacaoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/preventiva/templates': typeof PreventivaTemplatesRoute
  '/preventiva_/agendamentos': typeof PreventivaAgendamentosRoute
  '/satisfacao/$token': typeof SatisfacaoTokenRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/novo': typeof TicketsNovoRoute
  '/trabalhos_/$id': typeof TrabalhosIdRoute
  '/preventiva/': typeof PreventivaIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/preventiva_/execucao/$id': typeof PreventivaExecucaoIdRoute
  '/preventiva_/relatorio/$id': typeof PreventivaRelatorioIdRoute
  '/preventiva_/templates/$id': typeof PreventivaTemplatesIdRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/satisfacao/$token': typeof ApiPublicSatisfacaoTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/login'
    | '/preventiva'
    | '/tickets'
    | '/trabalhos'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/faturacao'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/preventiva/templates'
    | '/preventiva/agendamentos'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/trabalhos/$id'
    | '/preventiva/'
    | '/lovable/email/suppression'
    | '/preventiva/execucao/$id'
    | '/preventiva/relatorio/$id'
    | '/preventiva/templates/$id'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/satisfacao/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/login'
    | '/tickets'
    | '/trabalhos'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/faturacao'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/preventiva/templates'
    | '/preventiva/agendamentos'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/trabalhos/$id'
    | '/preventiva'
    | '/lovable/email/suppression'
    | '/preventiva/execucao/$id'
    | '/preventiva/relatorio/$id'
    | '/preventiva/templates/$id'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/satisfacao/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/login'
    | '/preventiva'
    | '/tickets'
    | '/trabalhos'
    | '/unsubscribe'
    | '/admin/emails'
    | '/admin/faturacao'
    | '/admin/tags'
    | '/admin/templates'
    | '/clientes/$id'
    | '/email/unsubscribe'
    | '/preventiva/templates'
    | '/preventiva_/agendamentos'
    | '/satisfacao/$token'
    | '/tickets/$id'
    | '/tickets/novo'
    | '/trabalhos_/$id'
    | '/preventiva/'
    | '/lovable/email/suppression'
    | '/preventiva_/execucao/$id'
    | '/preventiva_/relatorio/$id'
    | '/preventiva_/templates/$id'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/satisfacao/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PreventivaRoute: typeof PreventivaRouteWithChildren
  TicketsRoute: typeof TicketsRouteWithChildren
  TrabalhosRoute: typeof TrabalhosRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminFaturacaoRoute: typeof AdminFaturacaoRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PreventivaAgendamentosRoute: typeof PreventivaAgendamentosRoute
  SatisfacaoTokenRoute: typeof SatisfacaoTokenRoute
  TrabalhosIdRoute: typeof TrabalhosIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PreventivaExecucaoIdRoute: typeof PreventivaExecucaoIdRoute
  PreventivaRelatorioIdRoute: typeof PreventivaRelatorioIdRoute
  PreventivaTemplatesIdRoute: typeof PreventivaTemplatesIdRoute
  ApiPublicHooksAutoCloseTicketsRoute: typeof ApiPublicHooksAutoCloseTicketsRoute
  ApiPublicSatisfacaoTokenRoute: typeof ApiPublicSatisfacaoTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos': {
      id: '/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof TrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva': {
      id: '/preventiva'
      path: '/preventiva'
      fullPath: '/preventiva'
      preLoaderRoute: typeof PreventivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva/': {
      id: '/preventiva/'
      path: '/'
      fullPath: '/preventiva/'
      preLoaderRoute: typeof PreventivaIndexRouteImport
      parentRoute: typeof PreventivaRoute
    }
    '/trabalhos_/$id': {
      id: '/trabalhos_/$id'
      path: '/trabalhos/$id'
      fullPath: '/trabalhos/$id'
      preLoaderRoute: typeof TrabalhosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/novo': {
      id: '/tickets/novo'
      path: '/novo'
      fullPath: '/tickets/novo'
      preLoaderRoute: typeof TicketsNovoRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/satisfacao/$token': {
      id: '/satisfacao/$token'
      path: '/satisfacao/$token'
      fullPath: '/satisfacao/$token'
      preLoaderRoute: typeof SatisfacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva_/agendamentos': {
      id: '/preventiva_/agendamentos'
      path: '/preventiva/agendamentos'
      fullPath: '/preventiva/agendamentos'
      preLoaderRoute: typeof PreventivaAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva/templates': {
      id: '/preventiva/templates'
      path: '/templates'
      fullPath: '/preventiva/templates'
      preLoaderRoute: typeof PreventivaTemplatesRouteImport
      parentRoute: typeof PreventivaRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faturacao': {
      id: '/admin/faturacao'
      path: '/admin/faturacao'
      fullPath: '/admin/faturacao'
      preLoaderRoute: typeof AdminFaturacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva_/templates/$id': {
      id: '/preventiva_/templates/$id'
      path: '/preventiva/templates/$id'
      fullPath: '/preventiva/templates/$id'
      preLoaderRoute: typeof PreventivaTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva_/relatorio/$id': {
      id: '/preventiva_/relatorio/$id'
      path: '/preventiva/relatorio/$id'
      fullPath: '/preventiva/relatorio/$id'
      preLoaderRoute: typeof PreventivaRelatorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventiva_/execucao/$id': {
      id: '/preventiva_/execucao/$id'
      path: '/preventiva/execucao/$id'
      fullPath: '/preventiva/execucao/$id'
      preLoaderRoute: typeof PreventivaExecucaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/satisfacao/$token': {
      id: '/api/public/satisfacao/$token'
      path: '/api/public/satisfacao/$token'
      fullPath: '/api/public/satisfacao/$token'
      preLoaderRoute: typeof ApiPublicSatisfacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-close-tickets': {
      id: '/api/public/hooks/auto-close-tickets'
      path: '/api/public/hooks/auto-close-tickets'
      fullPath: '/api/public/hooks/auto-close-tickets'
      preLoaderRoute: typeof ApiPublicHooksAutoCloseTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface PreventivaRouteChildren {
  PreventivaTemplatesRoute: typeof PreventivaTemplatesRoute
  PreventivaIndexRoute: typeof PreventivaIndexRoute
}

const PreventivaRouteChildren: PreventivaRouteChildren = {
  PreventivaTemplatesRoute: PreventivaTemplatesRoute,
  PreventivaIndexRoute: PreventivaIndexRoute,
}

const PreventivaRouteWithChildren = PreventivaRoute._addFileChildren(
  PreventivaRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsNovoRoute: typeof TicketsNovoRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
  TicketsNovoRoute: TicketsNovoRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  LoginRoute: LoginRoute,
  PreventivaRoute: PreventivaRouteWithChildren,
  TicketsRoute: TicketsRouteWithChildren,
  TrabalhosRoute: TrabalhosRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminFaturacaoRoute: AdminFaturacaoRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PreventivaAgendamentosRoute: PreventivaAgendamentosRoute,
  SatisfacaoTokenRoute: SatisfacaoTokenRoute,
  TrabalhosIdRoute: TrabalhosIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PreventivaExecucaoIdRoute: PreventivaExecucaoIdRoute,
  PreventivaRelatorioIdRoute: PreventivaRelatorioIdRoute,
  PreventivaTemplatesIdRoute: PreventivaTemplatesIdRoute,
  ApiPublicHooksAutoCloseTicketsRoute: ApiPublicHooksAutoCloseTicketsRoute,
  ApiPublicSatisfacaoTokenRoute: ApiPublicSatisfacaoTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
